A few modified files after big av sync
Project.exports: tweaks for vivado, will not sync exactly with av in any case.
components/bias_spcm.rcc/bias_spcm.cc: fixed for newer namespaces
components/dds_complex.test/ddsTest.cxx: av sync
components/genExpected.test/genExpected.cxx: ditto
components/mixer_complex.test/mixerTest.cxx: ditto
components/unit.test/unitTest.cxx: ditto
runtime/application/src/ocpirun_main.cxx: ditto, plus tweak to "preliminary" feature message
runtime/ctests/src/run_tests.sh: allow to run in both bin directory and in src tree
tools/cdk/include/lib.mk: closer to av
tools/cdk/include/rcc/rcc-worker.mk: remove unused patchelf definition, fix indent
runtime/application/src/OcpiApplication.cxx: av sync except av version stuff
scripts/README: whitespace
tools/cdk/include/hdl/hdl-make.mk: av sync with issues conveyed to DB
tools/cdk/include/ocpisetup.mk: av sync, added comment about masking a bug
tools/cdk/include/util.mk: av sync
tools/cdk/include/hdl/quartus.mk: av sync
tools/cdk/include/lib.mk: av sync
tools/cdk/scripts/makeStaticWorker: av sync + OCPI_TOOL_HOST->OCPI_HOST_DIR
runtime/util/ezxml/include/OcpiUtilEzxml.h: undid x: attrs in favor of <extension>
runtime/util/ezxml/src/OcpiUtilEzxml.cxx: av sync, added <extension>, and unindent functionn
tools/cdk/scripts/ocpidev: av sync +
-- fix indent after <<-EOF
-- fix app-already-exists message
-- fix referencing getProjMetaData.py calls:
----- run it in $OCPI_CDK_DIR/scripts, do not assume it is in the user's path
----- do not run it after deleting a project

diff --git a/tools/cdk/scripts/makeStaticWorker b/tools/cdk/scripts/makeStaticWorker
--- a/tools/cdk/scripts/makeStaticWorker
+++ b/tools/cdk/scripts/makeStaticWorker
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+# This gets around some of the RPM-based limitations
+ocpixml=$(type -p ocpixml)
+[ -z ${ocpixml} ] && ocpixml=${OCPI_CDK_DIR}/bin/${OCPI_TOOL_DIR}/ocpixml
+[ -x ${ocpixml} ] || echo "Could not find ocpixml!"
+
+patchelf=$OCPI_PREREQUISITES_INSTALL_DIR/patchelf/bin/patchelf
+[ -x ${patchelf} ] || patchelf=$OCPI_PREREQUISITES_INSTALL_DIR/patchelf/$OCPI_TOOL_DIR/bin/patchelf
+[ -x ${patchelf} ] || echo "Could not find patchelf executable!"
+
 if test "$#" = 0; then
   echo This script takes a dynamic RCC worker artifact as input and creates one
   echo suitable for being dynamicly loaded into a statically linked executable.
@@ -14,7 +23,6 @@ T1=/tmp/makeStaticWorker$$.1
 T2=/tmp/makeStaticWorker$$.2
 set -e
 OUT=`dirname $1`/`basename $1 .so`_s.so
-ocpixml=$OCPI_CDK_DIR/bin/$OCPI_TOOL_DIR/ocpixml
 $ocpixml get $1 > $T1
 $ocpixml strip $1 $T2
 X=1
@@ -23,7 +31,7 @@ if ! grep '<artifact.*dynamic=.1' $T1 > /dev/null; then
 elif file $T2 | grep ELF > /dev/null; then
   shift
  for i in $*; do PARGS="$PARGS --remove-needed $i"; done
- $OCPI_PREREQUISITES_INSTALL_DIR/patchelf/$OCPI_TOOL_HOST/bin/patchelf $PARGS $T2
+ ${patchelf} $PARGS $T2
  sed "s/\(<artifact.*dynamic='\)./\10/" $T1 | $ocpixml add $T2 -
  cp $T2 $OUT
  chmod a+x $OUT
