Debugging ethernet and transport cleanup changes
adapt/os/ocpios/linux/src/OcpiOsSocket.cxx: deal with EINTR on recv (in the debugger)
core/container/hdl_container/impl/include/HdlOCCP.h: MAGIC extra parens
core/container/hdl_container/impl/include/PciDriver.h: enable usage by C programs
core/container/hdl_container/impl/src/HdlContainer.cxx: use ocpiDebug/Info, fix ESN access, hex endpoint addrs
core/container/hdl_container/impl/src/HdlDriver.cxx: esn access fixes (with new container name prefixes)
core/container/hdl_container/impl/src/PciDriver.cxx: hex ep addresses and accessor offset fix
core/dataplane/rdma_driver_interface/interfaces/include/OcpiBaseSmemServices.h: remove unused method
core/dataplane/rdma_driver_interface/interfaces/src/DtTransferInternal.cxx: take more care in setting std::vector
 -- enable more reuse of the same addCompatibleEndpoint function, with better error checking
core/dataplane/rdma_drivers/pci/include/DtPCIPioXfer.h: partially simplify now private create method
core/dataplane/rdma_drivers/pci/src/DtPCIPioXfer.cxx: simplify allocateEndpoint, divide up DMA memory better
 -- enable this transport to be used between processes, hex bus addresses for debug
core/dataplane/transport/impl/include/OcpiTransport.h: remove now-unused/collapsed method
 -- keep track of the transport session's endpoints more separately between local/remote
core/dataplane/transport/impl/src/OcpiCircuit.cxx: be explicit (local/remote) about searching for endpoints
core/dataplane/transport/impl/src/OcpiTransport.cxx: eliminate initial allocation of endpoints
 -- collapse getlocalendpoint methods to eliminate potential redundancy/bugs
 -- don't ever search for endpoints regardless of whether they are remote or local
core/local/util/driver/src/OcpiDriverManager.cxx: log config file device retrieval
test/hdl/scripts/loadBitStreamOnPlatform: error check when ESN/JTAG match fails in config file
test/hdl/src/getPci.h: fix magic so that old utilities still work

diff --git a/test/hdl/scripts/loadBitStreamOnPlatform b/test/hdl/scripts/loadBitStreamOnPlatform
--- a/test/hdl/scripts/loadBitStreamOnPlatform
+++ b/test/hdl/scripts/loadBitStreamOnPlatform
@@ -12,6 +12,10 @@ if [[ $# < 4 ]]; then
     echo '  'For now, you must select the correct USB port and part for the device.
     exit 1
 fi
+if [[ $5 == "" ]]; then
+    echo "No ESN found/specified in config file.  Can't load bitstream automatically." 1>&2
+    exit 1
+fi
 tmp=/tmp/ocpibitstream$$
 port=`echo listusbcables | $OCPI_XILINX_TOOLS_DIR/ISE/bin/lin64/impact -batch 2> $tmp | grep '^port=' | sed 's/port=\(.*\), *esn=\(.*\)/\1 \2/' | grep $5 | sed 's/^\([^ ]*\).*$/\1/'`
 `dirname $0`/loadBitStream $1 $2 $port $4
