Update PCI Vendor/Device ID handling to use the official PCI-SIG registered opencpi.org IDs -- also update flash loading scripts for PCI platforms
os/linux/driver/opencpi.c: probe for old and new device IDs
projects/assets/hdl/platforms/alst4/Makefile: change pci core to a library so IDs are parameters
projects/assets/hdl/platforms/ml605/Makefile: ditto
projects/assets/hdl/platforms/alst4x/Makefile: ditto
projects/assets/hdl/platforms/alst4/alst4.vhd: pass IDs into PCI code
projects/assets/hdl/platforms/ml605/ml605.vhd: ditto
projects/assets/hdl/platforms/alst4/alst4.xml: set this platform's pci device id from enum param
projects/assets/hdl/platforms/ml605/ml605.xml: ditto
projects/assets/hdl/platforms/ml605/loadFlash_ml605: fix verbose flag passthrough
projects/assets/hdl/platforms/ml605/ml605_pkg.vhd: add generics to pci code for IDs
projects/assets/hdl/platforms/ml605/pci_ml605.v: pass ID params down into actual PCI vendor core
projects/assets/hdl/primitives/stratix4/pci_alst4.v: ditto
projects/assets/hdl/primitives/pcie_4243_hip_s4gx_gen2_x4_128/Makefile: change from core to lib
projects/assets/hdl/primitives/pcie_4243_hip_s4gx_gen2_x4_128/pcie_hip_s4gx_gen2_x4_128_core.v:
-- pass ID params into encrypted core
projects/assets/hdl/primitives/pcie_4243_trn_v6_gtx_x4_250/Makefile: change from core to lib
projects/core/hdl/primitives/platform/platform_pkg.vhd: create a small package for PCI constants
projects/core/specs/platform-spec.xml: add a possible pci_device_id to all platforms
-- for now this is where these per-platform IDs will be registered.
runtime/hdl-support/src/ocfrp_check_main.cxx: update SW to use OU::probePci and new IDs
runtime/hdl/include/HdlPciDriver.h: define new PCI software constants and remove probePci
runtime/hdl/src/HdlPciDriver.cxx: remove old and use new OU::probePci with new PCI ID constants
runtime/util/misc/src/OcpiUtilPci.cxx: PCI utility moved out of HdlPciDriver.h
runtime/hdl-support/altera/altera.mk: find default altera tools location in homedir
-- support the altera kits dir
runtime/hdl-support/altera/loadFlash_altera: update for 1.3
runtime/hdl-support/scripts/loadFlash: ditto
runtime/hdl-support/xilinx/loadFlash_xilinx: ditto
runtime/container/src/ContainerManager.cxx: new linker symbols

diff --git a/runtime/hdl-support/altera/loadFlash_altera b/runtime/hdl-support/altera/loadFlash_altera
--- a/runtime/hdl-support/altera/loadFlash_altera
+++ b/runtime/hdl-support/altera/loadFlash_altera
@@ -20,37 +20,62 @@
 
 # A script for loading the user-bit-stream flash memory on altera development boards.
 
-if test "$OCPI_ALTERA_TOOLS_DIR" = "" -o "$OCPI_ALTERA_KITS_DIR" = ""; then
-  echo "Altera environment variables (OCPI_ALTERA_TOOLS_DIR and OCPI_ALTERA_KITS_DIR) are not set."
-  exit 1
-fi
-if test ! -d "$OCPI_ALTERA_TOOLS_DIR" -o ! -d "$OCPI_ALTERA_KITS_DIR" ; then
-  echo "Altera directories (set by OCPI_ALTERA_TOOLS_DIR and OCPI_ALTERA_KITS_DIR) do not exist."
-  exit 1
-fi
+[ "$1" = -v ] && {
+    verbose=1
+    shift
+}
+source $OCPI_CDK_DIR/scripts/util.sh
+setVarsFromMake $OCPI_CDK_DIR/include/hdl/altera.mk ShellQuartusVars=1 Verbose=$verbose
 if test $# != 5; then
   echo "This is an internal script meant to be called from a platform-specific script"
   echo "There must be four arguments, which are:"
+  echo "0. Optional -v for verbose"
   echo "1. The name of the board/kit as defined by Altera, e.g. stratixIVGX_4sgx530"
   echo "2. The name of the part as defined in the Altera kit, e.g. s4gx530".
   echo "3. The serial number in hex, of the jtag cable".
   echo "4. The flash memory offset for the board."
   echo "5. The bit file to write into the flash."
-  echo "See alternatives in the $OCPI_ALTERA_KITS_DIR directory (without the '_fpga' suffix)."
+  echo "See alternatives in the $OcpiAlteraKitsDir directory (without the '_fpga' suffix)."
   exit 1
 fi
-if test ! -d "$OCPI_ALTERA_KITS_DIR/"${1}_fpga; then
-  echo "There is no kit installed with the name $1 (no directory named $OCPI_ALTERA_KITS_DIR/${1}_fpga)."
-  exit 1
-fi
+[ -n "$verbose" ] && {
+  echo OcpiAlteraQuartusDir=$OcpiAlteraQuartusDir
+  echo OcpiAlteraProgrammerDir=$OcpiAlteraProgrammerDir
+  echo OcpiAlteraLicenseFile=$OcpiAlteraLicenseFile
 
-QBIN="$OCPI_ALTERA_TOOLS_DIR/quartus/bin"
-NBIN="$OCPI_ALTERA_TOOLS_DIR/nios2eds/bin"
-NTOP="$OCPI_ALTERA_TOOLS_DIR/nios2eds"
+}
+[ -z "$OcpiAlteraProgrammerDir" ] && {
+  echo Error: Could not find the directory for Altera Quartus or programming tools.
+  exit 1
+}
+QBIN="$OcpiAlteraProgrammerDir/quartus/bin"
+[ ! -d $QBIN ] && {
+  QBIN="$OcpiAlteraProgrammerDir/qprogrammer/bin"
+  [ ! -d $QBIN ] && {
+    echo Neither $OcpiAlteraProgrammerDir/quartus/bin nor $OcpiAlteraProgrammerDir/qprogrammer/bin exist
+    exit 1
+  }
+}
+if test ! -x "$QBIN"/jtagconfig -o ! -x "$QBIN/quartus_pgm"; then
+  echo With tools bin directory: $QBIN
+  echo "The required Altera executables (jtagconfig, quartus_pgm) are not present." 1>&2
+  exit 1
+fi
+# up to this point we are doing the same tests as for normal/jtag bitstream loading
+# now we start depending on the nios stuff that requires the full quartus installation...
+NTOP="$OcpiAlteraProgrammerDir/nios2eds"
 NBIN="$NTOP/bin"
 NSH="$NTOP/nios2_command_shell.sh"
-if test ! -x "$QBIN"/jtagconfig -o ! -x "$QBIN/quartus_pgm" -o ! -x "$NBIN/sof2flash" -o ! -x "$NBIN/nios2-flash-programmer" -o ! -x "$NSH"; then
+[ -x "$NBIN/sof2flash" -a -x "$NBIN/nios2-flash-programmer" -a -x "$NSH" ] || {
   echo "The required executables (jtagconfig, quartus_pgm, sof2flash, nios2-flash-programmer) are not present."
+  exit 1
+}
+if test ! -d "$OcpiAlteraKitsDir" -o ! -d "$OcpiAlteraKitsDir" ; then
+  echo "Altera directories (set by OCPI_ALTERA_DIR and OCPI_ALTERA_KITS_DIR) do not exist."
+  exit 1
+fi
+if test ! -d "$OcpiAlteraKitsDir/"${1}_fpga; then
+  echo "There is no kit installed with the name $1 (no directory named $OCPI_ALTERA_KITS_DIR/${1}_fpga)."
   exit 1
 fi
 
@@ -90,7 +115,7 @@ if test "$Found" = ""; then
   exit 1
 fi
 echo Using cable \"$Found\" with serial number $FSerial.
-FBS="$OCPI_ALTERA_KITS_DIR/"${1}_fpga/factory_recovery/${2}_fpga_bup.sof
+FBS="$OcpiAlteraKitsDir/"${1}_fpga/factory_recovery/${2}_fpga_bup.sof
 if test ! -r "$FBS"; then
   echo No readable factory bitstream. Looking for: \"$FBS\"
   exit 1
@@ -124,6 +149,7 @@ case $5 in
 esac
 
 echo Converting bitstream file \"$bitfile\" to flash format in \"$temp.flash\" using sof2flash
+echo This step takes a few minutes. Starting at `date`.
 echo "$NSH" sof2flash --input=$bitfile --output=$temp.flash --offset=$4 --pfl --optionbit=0x00018000 --programmingmode=PS > $temp.2
 "$NSH" sof2flash --input=$bitfile --output=$temp.flash --offset=$4 --pfl --optionbit=0x00018000 --programmingmode=PS >> $temp.2 2>&1
 if test $? != 0; then
@@ -133,14 +159,15 @@ fi
 rm $temp.2
 rm -f $temp.sof
 echo Loading factory bitstream \"$FBS\" to use for indirectly writing flash memory.
-echo "$OCPI_ALTERA_TOOLS_DIR"/quartus/bin/quartus_pgm -m jtag -c "$Found" -o "p;$FBS" > $temp.3
-"$OCPI_ALTERA_TOOLS_DIR"/quartus/bin/quartus_pgm -m jtag -c "$Found" -o "p;$FBS" >> $temp.3 2>&1
+echo $OcpiAlteraProgrammerDir/quartus/bin/quartus_pgm -m jtag -c "$Found" -o "p;$FBS" > $temp.3
+$OcpiAlteraProgrammerDir/quartus/bin/quartus_pgm -m jtag -c "$Found" -o "p;$FBS" >> $temp.3 2>&1
 if test $? != 0; then
   echo JTAG loading of the factory bitstream failed.  See log in $temp.3
   exit 1
 fi
 rm $temp.3
 echo JTAG Loading of the factory bitstream succeeded.  Now using it to write the flash.
+echo Starting to write the flash at `date`.
 echo "$NSH" nios2-flash-programmer --base 0x08000000 $temp.flash > $temp.4
 time "$NSH" nios2-flash-programmer --base 0x08000000 $temp.flash > $temp.5 2>$temp.6
 if test $? != 0; then
