More scrubbing/testing of standalone scenarios for zed hardware testing etc. -- ensure test-opencpi.sh works on zed -- ensure *everything* uses CDK rather than BASE -- ensure scripts operate in a default/empty environment -- make zed setup have no dev-env dependencies -- allow multiple kernel drivers for different kernels
os/linux/driver/ocpi_linux_driver: use kernel labels when loading drivers
-- more error checking env
-- remove unnecessary special case for deployed
platforms/zed/defaultsetup.sh: change "ROOT" to "CDK"
platforms/zed/defaultnetsetup.sh: another BASE->CDK fix
platforms/zed/makeSD.sh: include new file ocpibootstrap.sh
-- the runtime subset of what was in ocpisetup.sh
-- include potentially multiple drivers with different kernel tags
platforms/zed/zednetsetup.sh: do not do ocpisetup.sh, this is not a development env
-- just set the PATH, CDK_DIR and TOOL_HOST/DIR vars
scripts/makeExportLinks.sh: fewer messages when targets are not built
tools/cdk/scripts/ocpidriver: use ocpibootstrap to eliminate env dependency
tools/cdk/scripts/ocpisetup.sh: move run-time-only parts to ocpibootstrap.sh for sharing
Project.exports: add ocpibootstrap.sh
scripts/test-opencpi.sh: use minimal runtime bootstrap, not dev one, to run on SD card
tools/cdk/scripts/ocpibootstrap.sh: extracted from ocpisetup.sh for runtime-only
platforms/zed/zedsetup.sh: ROOT -> CDK
-- and remote copy of libstdc++

diff --git a/os/linux/driver/ocpi_linux_driver b/os/linux/driver/ocpi_linux_driver
--- a/os/linux/driver/ocpi_linux_driver
+++ b/os/linux/driver/ocpi_linux_driver
@@ -6,7 +6,10 @@
 # Retrieve the reserved DMA memory value from the kernel command line
 # Note there might be multiple reservations, and we currently only support one (the first).
 
-source $OCPI_CDK_DIR/scripts/ocpisetup.sh $OCPI_CDK_DIR/scripts/ocpisetup.sh
+if test "$OCPI_CDK_DIR" = "" -o "$OCPI_TOOL_HOST" = ""; then
+  echo Error: this script "($0)" cannot be run without OCPI_CDK_DIR and OCPI_TOOL_HOST.
+fi
+
 MODNAME=opencpi
 SUDO=sudo
 MODFILE=$MODNAME.ko
@@ -30,22 +33,29 @@ fi
 if [ $# = 2 ] ; then # this is for the makefile
   DIR=.
 else
-  # if we are in a bin directory, we are in a standalone/embedded mode
-  DIR=`dirname $0`
-  DNAME=`basename $DIR`
-  if [ "$DNAME" = bin ] ; then
-    DIR="$DIR/../lib"
-  else
+#  There is no difference anymore to require this distinction
+#  For lots of reasons the standalone system still has the target subdir
+# if we are in a bin directory, we are in a standalone/embedded mode
+#  DIR=`dirname $0`
+#  DNAME=`basename $DIR`
+#  if [ "$DNAME" = bin ] ; then
+#    DIR="$DIR/../lib"
+#  else
     DIR=$OCPI_CDK_DIR/lib/$OCPI_TOOL_HOST
-    if test ! -e $DIR/$MODFILE; then
-      REL=`uname -r | sed 's/-dirty//'`
-      DIR2=$OCPI_CDK_DIR/driver/$REL/target-$OCPI_TOOL_HOST
-      if test ! -e $DIR2/$MODFILE; then
-        echo Error: cannot find driver/file $MODFILE in $DIR or $DIR2
-        exit 1
-      fi
-      DIR=$DIR2
-    fi
+#  fi
+  if test -f /etc/ocpi-release; then
+     LABEL=$(< /etc/ocpi-release)
+  else
+     LABEL=$(uname -r)
+  fi
+  if test -e $DIR/$MODNAME-$LABEL.ko; then
+    MODFILE=$MODNAME-$LABEL.ko
+  else
+    MODFILE=$MODNAME.ko
+  fi
+  if test ! -e $DIR/$MODFILE; then
+    echo Error: cannot find driver/file "$MODNAME*.ko" in $DIR
+    exit 1
   fi
 fi
 MODPATH=$DIR/$MODFILE
