misc minor updates that were queued up behind the unit test work
hdl/platforms/zed/zed.mk: add HdlRccPlatform
os/linux/driver/ocpi_linux_driver: more carefully search for the driver file
runtime/dataplane/rdma_smb/linux/src/OcpiPosixFileMappingServices.cxx: use arch, not os for zynq
platforms/zynq/gdbForZynq.sh: make more usable for any zynq platform target
runtime/hdl/src/HdlDevice.cxx: tolerate quietly certain old PCI cards that probe badly
runtime/hdl/src/HdlLSimDevice.cxx: fix OCPI_HDL_SIMULATOR(S) to be exclusive and mandatory
scripts/makeExportLinks.sh: deal with lock files with '#' in their names, and bsd xargs w/o -r
scripts/setup-install.sh: deal with OCPI_PREREQUISITES_DIR better
tools/cdk/include/ocpisetup.mk: add -Wextra and -pipe and, for C, -std=c99

diff --git a/os/linux/driver/ocpi_linux_driver b/os/linux/driver/ocpi_linux_driver
--- a/os/linux/driver/ocpi_linux_driver
+++ b/os/linux/driver/ocpi_linux_driver
@@ -36,40 +36,42 @@ fi
 if [ $(id -u) = 0 ]; then
   SUDO=
 fi
-if [ $# = 2 ] ; then # this is for the makefile
-  DIR=.
+##########################################################################################
+# Determine where the driver lives, setting DIR and MODFILE
+if [ $# = 2 ] ; then # this is called from the makefile when we are loading what we are building
+  DIR=./target-$OCPI_TOOL_DIR
 else
-#  There is no difference anymore to require this distinction
-#  For lots of reasons the standalone system still has the target subdir
-# if we are in a bin directory, we are in a standalone/embedded mode
-#  DIR=`dirname $0`
-#  DNAME=`basename $DIR`
-#  if [ "$DNAME" = bin ] ; then
-#    DIR="$DIR/../lib"
-#  else
-    DIR=$OCPI_CDK_DIR/lib/$OCPI_TOOL_DIR
-#  fi
-  if test -f /etc/ocpi-release; then
-     LABEL=$(cat /etc/ocpi-release)
+  # Determine the kernel release tag when there could be multiple drivers around
+  # If the /etc/opencpi-release file exists, it tells us our own release tag and label for the driver
+  if test -f /etc/opencpi-release; then
+    read x y LABEL < /etc/opencpi-release
+  # The /etc/ocpi-release file is deprecated, and only held the kernel label
+  elif test -f /etc/ocpi-release; then
+    LABEL=$(cat /etc/ocpi-release)
   else
-     LABEL=$(uname -r)
+    LABEL=$(uname -r)
   fi
-  if test -e $DIR/$MODNAME-$LABEL.ko; then
-    MODFILE=$MODNAME-$LABEL.ko
-  fi
-  if test -d /opt/opencpi/driver/; then
-    # RPM-based install
-    DIR=/opt/opencpi/driver/$(uname -r)
-  fi
-  if test ! -e $DIR/$MODFILE; then
-    echo Error: cannot find driver/file "$MODNAME*.ko" in $DIR
-    exit 1
+  # Look for a driver most-specific to least specific
+  DIR=$OCPI_CDK_DIR/lib/$OCPI_TOOL_DIR
+  DIR2=/opt/opencpi/driver/$(uname -r)
+  MODFILE=$MODNAME-$LABEL.ko
+  MODFILE2=$MODNAME.ko
+  if test -e $DIR/$MODFILE; then
+    true # default
+  elif test -e $DIR2/$MODFILE; then
+    DIR=$DIR2
+  elif test -e $DIR/$MODFILE2; then
+    MODFILE=$MODFILE2
+  elif test -e $DIR2/$MODFILE2; then
+    DIR=$DIR2
+    MODFILE=$MODFILE2
   fi
 fi
-
-if test -r /opt/opencpi/driver/$(uname -r)/${MODFILE}; then
-  DIR=/opt/opencpi/driver/$(uname -r)
+if test "$1" = load -a ! -e $DIR/$MODFILE; then
+  echo Error: cannot find driver/file "$MODNAME*.ko".
+  exit 1
 fi
+######## DIR and MODFILE are set and the driver file is verified to exist
 
 MODPATH=$DIR/$MODFILE
 RULESPATH=$DIR/$RULESFILE
@@ -95,7 +97,6 @@ rmd () {
   rudev
 }
 
-
 if [ -d /sys/module/opencpi ] ; then
    case $1 in
      (reload)
@@ -117,8 +118,8 @@ if [ -d /sys/module/opencpi ] ; then
        ;;
   esac
 elif [ $1 = unload ] ; then
-    echo The driver module is not loaded.  No action was taken.
-    exit 0
+  echo The driver module is not loaded.  No action was taken.
+  exit 0
 fi
 # AV-1715 - look for opencpi_memmap explicitly first
 MEMMAP=`tr ' ' '\n' < /proc/cmdline | grep -m 1 '^opencpi_memmap='`
@@ -177,7 +178,12 @@ else
   $SUDO cp $RULESPATH /etc/udev/rules.d &&
   $SUDO $RELOAD
   if test $? != 0; then
-    exit 1
+    echo "Reload of udev rules failed. ($RELOAD)"
+    if [ "$($SUDO stat -c %d:%i /)" == "$($SUDO stat -c %d:%i /proc/1/root/.)" ]; then
+      exit 1
+    else
+      echo "Detected chroot environment. Continuing anyway."
+    fi
   fi
 fi
 $SUDO /sbin/insmod $MODPATH $INSARG
